clima_class_application:
    resource: "@ClimaClassApplicationBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /fos
    
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"